#!/root/.nvm/v0.10.12/bin/node
var fork, hubotPath, startDubot, stopDubot, restartDubot;

fork = require('child_process').fork;
hubotPath = __dirname + '/node_modules/hubot/bin/';

startDubot = function (stop, restart) {
	var dubot = fork(
		hubotPath + 'hubot',
		[],
		{
			cwd: __dirname,
			execPath: 'coffee'
		}
	);
	
	dubot.on('reboot', function () {
		restart(dubot);
	});

	dubot.on('poweroff', function () {
		stop(dubot);
	});
};

stopDubot = function (dubot) {
	dubot.exit(0);
	process.exit(0);
};

restartDubot = function (dubot) {
	dubot.exit(0);
	startDubot(stopDubot, restartDubot);
};

startDubot(stopDubot, restartDubot);
