#!/bin/bash
export HUBOT_AUTH_ADMIN="kc,kingcody,k1n9c0dy,asmundr,torphal,skinnypup,plotta"
export HUBOT_IRC_SERVER="irc.torpnet.us"
export HUBOT_IRC_ROOMS="#linux"
#,#milledgeville,#torpnest"
export HUBOT_IRC_NICK="Dubot"
export HUBOT_IRC_PORT="6669"
export HUBOT_IRC_SERVER_FAKE_SSL="true"
export HUBOT_IRC_USESSL="true"
export HUBOT_IRC_REJOIN="true"
export HUBOT_BRAIN_AUTOSAVE="true"
export HUBOT_BRAIN_AUTOSAVE_INTERVAL="60"


export HUBOT_LOG_LEVEL="debug" # Debug INFO

echo ""
echo "Starting Hubot"
./bin/hubot --name Dubot --adapter irc &
